version: '3.8'

services:
  app:
    image: ildusakhmadiev/learning-app:1.0-full
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
      - python-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/learning
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Tw2dj4dis5D
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FLASK_SERVER_URL=http://python-service:5000/transcribe
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=learning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tw2dj4dis5D
    ports:
      - "5433:5432"
    networks:
      - app-network

  python-service:
    image: ildusakhmadiev/learning-app-python:1.0
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: