version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/learning
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Tw2dj4dis5D
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # Убедитесь, что URL корректный, если сервис Flask не используется
      - FLASK_SERVER_URL=http://localhost:5000/transcribe
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=learning
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tw2dj4dis5D
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: